name: Build NanoDHCP Native Binaries

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This tells GitHub to run this exact job twice: once on Linux, once on Windows
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # You can change this to 17 if you prefer
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile Java & Build JAR (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p build
          javac -d build src/*.java src/Common/*.java src/DHCP/*.java src/DHCP/lease/*.java src/DHCP/handlers/*.java
          jar cfe NanoDHCP.jar NanoDHCP -C build .

      - name: Compile Java & Build JAR (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          javac -d build src\*.java src\Common\*.java src\DHCP\*.java src\DHCP\lease\*.java src\DHCP\handlers\*.java
          jar cfe NanoDHCP.jar NanoDHCP -C build .

      - name: Build Native Image
        run: native-image --no-fallback -jar NanoDHCP.jar

      - name: Upload Linux Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: NanoDHCP-Linux
          path: nanodhcp

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: NanoDHCP-Windows
<<<<<<< HEAD
          path: NanoDHCP.exe
=======
          path: NanoDHCP.exe
>>>>>>> 33c78862c6e3572ecdfae9d5428bbff340452f0a
